tf import

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -45,6 +45,15 @@ jobs:
         run: terraform init
         working-directory: terraform/
 
+      # Import Resources
+      - name: Import Resources
+        run: |
+          terraform state rm aws_s3_bucket.terraform_state || echo "Resource not found in state, continuing..."
+          terraform import aws_s3_bucket.terraform_state bsf-terraform-state-bucket
+          terraform import aws_dynamodb_table.terraform_lock bsf-terraform-lock-table
+          terraform import aws_s3_bucket.bsf_bucket bsf-bucket
+        working-directory: terraform/
+
       - name: Terraform Plan
         env:
           TF_LOG: DEBUG
